export const profile = {
  name: "Zeeshan",
  role: "Full stack engineer",
  bio: "focused on creating innovative and modern web & mobile apps. With a passion for continuous improvement, I thrive on bringing creative ideas to life through technology.",
  availability: "open to freelance work and full-time opportunities.",
  githubUsername: "thezeeshann",
  socials: {
    twitter: "https://twitter.com/thezeeshann",
    github: "https://github.com/thezeeshann",
    linkedin: "https://www.linkedin.com/in/thezeeshannn",
    email: "mailto:info.zeeshann@gmail.com",
  },
};

export const music = {
  videoId: "8kooIgKESYE",
  title: "Hans Zimmer — Interstellar",
  url: "https://www.youtube.com/watch?v=8kooIgKESYE",
};

// `icon` is a simpleicons.org slug, or null where the brand has none.
export const skills = [
  { name: "JavaScript", icon: "javascript" },
  { name: "TypeScript", icon: "typescript" },
  { name: "React.js", icon: "react" },
  { name: "Next.js", icon: "nextdotjs" },
  { name: "Tailwind CSS", icon: "tailwindcss" },
  { name: "ShadCN UI", icon: "shadcnui" },
  { name: "Redux", icon: "redux" },
  { name: "RTK Query", icon: "redux" },
  { name: "Tanstack Query", icon: "reactquery" },
  { name: "React Hook Form", icon: "reacthookform" },
  { name: "React Native", icon: "react" },
  { name: "Expo", icon: "expo" },
  { name: "Node.js", icon: "nodedotjs" },
  { name: "Express.js", icon: "express" },
  { name: "Hono", icon: "hono" },
  { name: "PostgreSQL", icon: "postgresql" },
  { name: "MongoDB", icon: "mongodb" },
  { name: "Prisma ORM", icon: "prisma" },
  { name: "Drizzle ORM", icon: "drizzle" },
  { name: "Supabase", icon: "supabase" },
  { name: "Better Auth", icon: "betterauth" },
  { name: "LLM Integrations", icon: null },
  { name: "Git", icon: "git" },
  { name: "GitHub", icon: "github" },
  { name: "Linux", icon: "linux" },
  { name: "Docker", icon: "docker" },
  { name: "AWS", icon: null },
  { name: "Vercel", icon: "vercel" },
  { name: "Sentry", icon: "sentry" },
  { name: "Better Stack", icon: null },
];

export const experience = [
  {
    id: 1,
    current: true,
    role: "Full Stack Engineer",
    company: "Slarity",
    companyUrl: "",
    employmentType: "Full-time",
    duration: "May 2025 — Present",
    location: "Chennai",
    techstacks: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Hono",
      "Supabase",
      "Drizzle ORM",
      "PostgreSQL",
      "Typesense",
      "LLMs",
      "TimescaleDB",
    ],
    points: [
      "Built and scaled high-performance search functionality using Typesense, indexing and querying 4+ million products, significantly improving search accuracy and response times.",
      "Led development of the Admin Portal frontend, building reusable UI components using React.js, TypeScript, and Tailwind CSS to manage large product catalogs efficiently.",
      "Designed and developed backend APIs using TypeScript and Hono to interact with LLMs, processing and storing AI-generated responses in PostgreSQL via Drizzle ORM.",
      "Contributed to React Native applications, building UI components and integrating APIs for cross-platform mobile experiences.",
      "Implemented time-series data storage using PostgreSQL with TimescaleDB and added structured backend logging with Pino, improving observability, analytics, and production debugging.",
    ],
  },
  {
    id: 2,
    role: "Full-stack Developer",
    company: "ClumpCoder",
    companyUrl: "",
    employmentType: "Full-time",
    duration: "Aug 2024 — May 2025",
    location: "Mumbai, India",
    techstacks: [
      "React.js",
      "Tailwind CSS",
      "Redux",
      "Node.js",
      "Express.js",
      "MySQL",
      "Sequelize ORM",
      "AWS EC2",
      "Linux",
    ],
    points: [
      "Designed user interfaces with React.js and Tailwind CSS, integrating APIs with Redux for efficient state management and seamless client-server interaction.",
      "Developed and maintained RESTful APIs using Node.js, Express.js, MySQL, and Sequelize ORM, ensuring efficient data management.",
      "Collaborated with front-end teams to integrate APIs, ensuring seamless communication between server and client-side applications.",
      "Deployed backend services on AWS EC2 instances and utilized Linux for efficient server management and monitoring.",
    ],
  },
];

export const projects = [
  {
    id: 1,
    name: "Habitly",
    description:
      "A clean, free, no-account habit tracker for macOS. Track daily habits with streaks, a weekly grid, and progress graphs — all data stays local on-device, no account or network calls required.",
    techstacks: ["Electron", "Vite", "TypeScript", "React 19", "electron-store"],
    github: "https://github.com/thezeeshann/habitly",
    live: "https://habitly-6mv4.vercel.app/",
  },
  {
    id: 2,
    name: "Workout CMS",
    description:
      "A content management system for tracking and organizing workouts, with authentication, a PostgreSQL database, and a modern component-driven UI.",
    techstacks: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Drizzle ORM",
      "PostgreSQL",
      "Better Auth",
      "React Query",
      "shadcn/ui",
    ],
    github: "https://github.com/thezeeshann/workout-cms",
  },
  {
    id: 3,
    name: "Testimonial",
    description: "Get testimonials from your customers with ease.",
    techstacks: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "React Query",
      "PostgreSQL",
      "NextAuth",
      "Prisma",
      "Zod",
      "Uploadthing",
    ],
    github: "https://github.com/thezeeshann/testimonial",
  },
  {
    id: 4,
    name: "Ecommerce Application",
    description:
      "A full-featured ecommerce web application built on the MERN stack, with cart, catalog, and order flows.",
    techstacks: [
      "React.js",
      "JavaScript",
      "Tailwind CSS",
      "shadcn/ui",
      "Redux",
      "RTK Query",
      "Node.js",
      "Express.js",
      "MongoDB",
    ],
    github: "https://github.com/thezeeshann/ecommerce-mern",
  },
];
